apiVersion: v1
kind: Service
metadata:
  name: iweblens-svc
spec:
  type: NodePort
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
    nodePort: 30003
  selector:
    app: iweblenspod
